export type QuestionType = "text" | "radio" | "checkbox" | "checkbox-with-other"

export interface FormQuestion {
  id: number
  text: string
  subtitle?: string
  type: QuestionType
  fieldName: string
  options?: { value: string; label: string }[]
  required: boolean
  otherFieldName?: string
}

export const formQuestions: FormQuestion[] = [

  {
    id: 1,
    text: "Have you ever been treated for or diagnosed with any of the following medical conditions?",
    subtitle: "We're asking again to confirm we've heard you correctly and support your unique needs.",
    type: "checkbox",
    fieldName: "medicalConditions",
    options: [
      { value: "type1-diabetes", label: "Type I diabetes" },
      { value: "type2-diabetes", label: "Type II diabetes" },
      { value: "hyperthyroidism", label: "Hyperthyroidism" },
      { value: "hypothyroidism", label: "Hypothyroidism" },
      { value: "other-endocrine", label: "Other endocrine issues" },
      { value: "pcos", label: "Polycystic ovary syndrome (PCOS)" },
      { value: "bipolar", label: "Bipolar disorder (manic depression)" },
      { value: "depression", label: "Depression" },
      { value: "migraine", label: "Migraine or severe headaches" },
      { value: "lung-disease", label: "Lung disease" },
      { value: "glaucoma", label: "Glaucoma" },
      { value: "kidney-stones", label: "Kidney stones" },
      { value: "anxiety", label: "Anxiety disorder Agitation" },
      { value: "substance-use", label: "Substance use disorder" },
      { value: "insomnia", label: "Insomnia" },
      { value: "medullary-thyroid", label: "Medullary thyroid cancer (or a family history of diagnosis)" },
      { value: "thyroid-cancer", label: "Thyroid cancer" },
      { value: "multiple-endocrine", label: "Multiple endocrine neoplasia syndrome type 2" },
      { value: "diabetic-ketoacidosis", label: "Diabetic ketoacidosis" },
      { value: "diabetic-retinopathy", label: "Diabetic retinopathy" },
      { value: "prediabetes", label: "Prediabetes" },
      { value: "impaired-glucose", label: "Impaired fasting glucose" },
      { value: "gestational-diabetes", label: "Gestational diabetes" },
      { value: "chronic-kidney", label: "Chronic kidney disease" },
      { value: "coronary-artery", label: "Coronary artery disease" },
      { value: "arrhythmias", label: "Arrhythmias" },
      { value: "liver-disease", label: "Liver disease" },
      { value: "seizures", label: "Seizures" },
      { value: "none", label: "None / NA" },
    ],
    required: true,
  },
  {
    id: 2,
    text: "Do you experience any of the following?",
    subtitle: "Please check all that apply.",
    type: "checkbox",
    fieldName: "symptoms",
    options: [
      { value: "fatigue", label: "Fatigue, lethargy, or malaise" },
      { value: "headaches", label: "Headaches" },
      { value: "migraines", label: "Migraines" },
      { value: "walking-difficulty", label: "Difficulty with walking" },
      { value: "balance-difficulty", label: "Difficulty with balance" },
      { value: "unsteadiness", label: "Unsteadiness on feet" },
      { value: "dizziness", label: "Dizziness" },
      { value: "dyspnea", label: "Dyspnea (shortness of breath) on exertion" },
      { value: "insomnia", label: "Insomnia" },
      { value: "agitation", label: "Agitation" },
      { value: "acne", label: "Acne" },
      {
        value: "hyperandrogenism",
        label:
          "Hyperandrogenism (features of acne, irregular periods, deep voice, excessive hair, male pattern hair loss)",
      },
      { value: "irregular-periods", label: "Irregular periods" },
      { value: "perimenopause", label: "Peri-menopause" },
      { value: "none", label: "None / NA" },
    ],
    required: true,
  },
  {
    id: 3,
    text: "Have you ever been diagnosed with any other medical conditions?",
    type: "text",
    fieldName: "otherMedicalConditions",
    required: false,
  },
  {
    id: 4,
    text: "Are you currently taking any medications?",
    type: "radio",
    fieldName: "takingMedications",
    options: [
      { value: "yes", label: "Yes" },
      { value: "no", label: "No" },
    ],
    required: true,
  },
  {
    id: 5,
    text: "Have you ever taken any of the following medications?",
    subtitle: "Please check all that apply.",
    type: "checkbox",
    fieldName: "medicationsTaken",
    options: [
      { value: "byetta", label: "BYETTA® (exenatide)" },
      { value: "metformin", label: "Metformin" },
      { value: "bupropion", label: "Bupropion based medication (Bupron, Zupion, Bupraset, Zyban, Smoquit)" },
      { value: "victoza", label: "Victoza® (liraglutide)" },
      { value: "xenical", label: "XENICAL® (orlistat)" },
      { value: "semaglutide", label: "Ozempic®, Wegovy® or RYBELSUS® (semaglutide)" },
      { value: "mounjaro", label: "Mounjaro® (tirzepatide)" },
      { value: "trulicity", label: "Trulicity® (dulaglutide)" },
      { value: "bydureon", label: "BYDUREON" },
      { value: "none", label: "None" },
    ],
    required: true,
  },
  {
    id: 6,
    text: "Do any of the following apply to you?",
    subtitle: "Please check all that apply.",
    type: "checkbox",
    fieldName: "healthConditions",
    options: [
      { value: "cyclosporine", label: "Taking cyclosporine or warfarin" },
      { value: "organ-transplant", label: "Had an organ transplant" },
      { value: "food-absorption", label: "Have been diagnosed with problems absorbing food" },
      { value: "gallbladder", label: "Have had gallbladder problems and still have your gallbladder" },
      { value: "pancreatitis", label: "Have had pancreatitis" },
      { value: "none", label: "None / NA" },
    ],
    required: true,
  },
  {
    id: 7,
    text: "Have you ever had any surgeries?",
    type: "radio",
    fieldName: "hadSurgeries",
    options: [
      { value: "yes", label: "Yes" },
      { value: "no", label: "No" },
    ],
    required: true,
  },
  {
    id: 8,
    text: "Have you had a provider listen to your heart and document a normal heart exam within the past 12 months?",
    type: "radio",
    fieldName: "normalHeartExam",
    options: [
      { value: "yes", label: "Yes" },
      { value: "no", label: "No" },
    ],
    required: true,
  },
  {
    id: 9,
    text: "Do you know your blood pressure range from within the last 6 months?",
    subtitle: "If taking blood pressure medication, this should be your range on medication.",
    type: "radio",
    fieldName: "bloodPressure",
    options: [
      { value: "low", label: "Low (Less than 90/60 mmHg)" },
      { value: "normal", label: "Normal (91-129/61-84 mmHg)" },
      { value: "high", label: "High (Higher than 130/85 mmHg)" },
      { value: "unknown", label: "I don't know" },
    ],
    required: true,
  },
  {
    id: 10,
    text: "What is your waist circumference?",
    subtitle: "You can measure your waist circumference at the level of your belly button.",
    type: "radio",
    fieldName: "waistCircumference",
    options: [
      { value: "less-than-35", label: "Less than 35 inches" },
      { value: "35-39", label: "35 - 39 inches" },
      { value: "40-or-more", label: "40 inches or more" },
      { value: "unknown", label: "I don't know" },
    ],
    required: true,
  },
  {
    id: 11,
    text: "Do you know your triglyceride levels?",
    subtitle: "Knowing your triglyceride levels can help us understand your risk of heart disease.",
    type: "radio",
    fieldName: "triglycerideLevel",
    options: [
      { value: "100-or-lower", label: "100 (mg/dL) or lower" },
      { value: "100-149", label: "100 - 149 (mg/dL)" },
      { value: "150-or-higher", label: "150 (mg/dL) or higher" },
      { value: "unknown", label: "I don't know" },
    ],
    required: true,
  },
  {
    id: 12,
    text: "Do you know your fasting blood sugar (glucose) level?",
    subtitle:
      "Checking your fasting glucose levels helps assess your risk for diabetes and understand how your body processes sugar.",
    type: "radio",
    fieldName: "fastingGlucose",
    options: [
      { value: "74-or-lower", label: "74 (mg/dL) or lower" },
      { value: "75-99", label: "75 - 99 (mg/dL)" },
      { value: "100-or-higher", label: "100 (mg/dL) or higher" },
      { value: "unknown", label: "I don't know" },
    ],
    required: true,
  },
  {
    id: 13,
    text: "Do you know your high-density lipoprotein (HDL) cholesterol level?",
    subtitle: "Monitoring HDL cholesterol levels is important for understanding cardiovascular health.",
    type: "radio",
    fieldName: "hdlCholesterol",
    options: [
      { value: "40-or-lower", label: "40 (mg/dL) or lower" },
      { value: "41-50", label: "41 - 50 (mg/dL)" },
      { value: "50-or-higher", label: "50 (mg/dL) or higher" },
      { value: "unknown", label: "I don't know" },
    ],
    required: true,
  },
]