export type QuestionType = "text" | "radio" | "checkbox" | "checkbox-with-other"

export interface FormQuestion {
  id: number
  text: string
  subtitle?: string
  type: QuestionType
  fieldName: string
  options?: { value: string; label: string }[]
  required: boolean
  otherFieldName?: string
}

export const formQuestions: FormQuestion[] = [
  {
    id: 1,
    text: "What is your complete address?",
    type: "text",
    fieldName: "address",
    required: true,
  },
  {
    id: 2,
    text: "What is your occupation? (optional)",
    type: "text",
    fieldName: "occupation",
    required: false,
  },
  {
    id: 3,
    text: "What is your marital status?",
    type: "radio",
    fieldName: "maritalStatus",
    options: [
      { value: "single", label: "Single (never married) Domestic Partner" },
      { value: "married", label: "Married" },
      { value: "widowed", label: "Widowed" },
      { value: "separated", label: "Separated" },
      { value: "prefer-not-to-say", label: "I prefer not to answer" },
    ],
    required: true,
  },
  {
    id: 4,
    text: "Have you ever been treated for or diagnosed with any of the following medical conditions?",
    subtitle: "We're asking again to confirm we've heard you correctly and support your unique needs.",
    type: "checkbox",
    fieldName: "medicalConditions",
    options: [
      { value: "type1-diabetes", label: "Type I diabetes" },
      { value: "type2-diabetes", label: "Type II diabetes" },
      { value: "hyperthyroidism", label: "Hyperthyroidism" },
      { value: "hypothyroidism", label: "Hypothyroidism" },
      { value: "other-endocrine", label: "Other endocrine issues" },
      { value: "pcos", label: "Polycystic ovary syndrome (PCOS)" },
      { value: "bipolar", label: "Bipolar disorder (manic depression)" },
      { value: "depression", label: "Depression" },
      { value: "migraine", label: "Migraine or severe headaches" },
      { value: "lung-disease", label: "Lung disease" },
      { value: "glaucoma", label: "Glaucoma" },
      { value: "kidney-stones", label: "Kidney stones" },
      { value: "anxiety", label: "Anxiety disorder Agitation" },
      { value: "substance-use", label: "Substance use disorder" },
      { value: "insomnia", label: "Insomnia" },
      { value: "medullary-thyroid", label: "Medullary thyroid cancer (or a family history of diagnosis)" },
      { value: "thyroid-cancer", label: "Thyroid cancer" },
      { value: "multiple-endocrine", label: "Multiple endocrine neoplasia syndrome type 2" },
      { value: "diabetic-ketoacidosis", label: "Diabetic ketoacidosis" },
      { value: "diabetic-retinopathy", label: "Diabetic retinopathy" },
      { value: "prediabetes", label: "Prediabetes" },
      { value: "impaired-glucose", label: "Impaired fasting glucose" },
      { value: "gestational-diabetes", label: "Gestational diabetes" },
      { value: "chronic-kidney", label: "Chronic kidney disease" },
      { value: "coronary-artery", label: "Coronary artery disease" },
      { value: "arrhythmias", label: "Arrhythmias" },
      { value: "liver-disease", label: "Liver disease" },
      { value: "seizures", label: "Seizures" },
      { value: "none", label: "None / NA" },
    ],
    required: true,
  },
  {
    id: 5,
    text: "Do you experience any of the following?",
    subtitle: "Please check all that apply.",
    type: "checkbox",
    fieldName: "symptoms",
    options: [
      { value: "fatigue", label: "Fatigue, lethargy, or malaise" },
      { value: "headaches", label: "Headaches" },
      { value: "migraines", label: "Migraines" },
      { value: "walking-difficulty", label: "Difficulty with walking" },
      { value: "balance-difficulty", label: "Difficulty with balance" },
      { value: "unsteadiness", label: "Unsteadiness on feet" },
      { value: "dizziness", label: "Dizziness" },
      { value: "dyspnea", label: "Dyspnea (shortness of breath) on exertion" },
      { value: "insomnia", label: "Insomnia" },
      { value: "agitation", label: "Agitation" },
      { value: "acne", label: "Acne" },
      {
        value: "hyperandrogenism",
        label:
          "Hyperandrogenism (features of acne, irregular periods, deep voice, excessive hair, male pattern hair loss)",
      },
      { value: "irregular-periods", label: "Irregular periods" },
      { value: "perimenopause", label: "Peri-menopause" },
      { value: "none", label: "None / NA" },
    ],
    required: true,
  },
  {
    id: 6,
    text: "Have you ever been diagnosed with any other medical conditions?",
    type: "text",
    fieldName: "otherMedicalConditions",
    required: false,
  },
  {
    id: 7,
    text: "Are you currently taking any medications?",
    type: "radio",
    fieldName: "takingMedications",
    options: [
      { value: "yes", label: "Yes" },
      { value: "no", label: "No" },
    ],
    required: true,
  },
  {
    id: 8,
    text: "Have you ever taken any of the following medications?",
    subtitle: "Please check all that apply.",
    type: "checkbox",
    fieldName: "medicationsTaken",
    options: [
      { value: "byetta", label: "BYETTA® (exenatide)" },
      { value: "metformin", label: "Metformin" },
      { value: "bupropion", label: "Bupropion based medication (Bupron, Zupion, Bupraset, Zyban, Smoquit)" },
      { value: "victoza", label: "Victoza® (liraglutide)" },
      { value: "xenical", label: "XENICAL® (orlistat)" },
      { value: "semaglutide", label: "Ozempic®, Wegovy® or RYBELSUS® (semaglutide)" },
      { value: "mounjaro", label: "Mounjaro® (tirzepatide)" },
      { value: "trulicity", label: "Trulicity® (dulaglutide)" },
      { value: "bydureon", label: "BYDUREON" },
      { value: "none", label: "None" },
    ],
    required: true,
  },
  {
    id: 9,
    text: "Do any of the following apply to you?",
    subtitle: "Please check all that apply.",
    type: "checkbox",
    fieldName: "healthConditions",
    options: [
      { value: "cyclosporine", label: "Taking cyclosporine or warfarin" },
      { value: "organ-transplant", label: "Had an organ transplant" },
      { value: "food-absorption", label: "Have been diagnosed with problems absorbing food" },
      { value: "gallbladder", label: "Have had gallbladder problems and still have your gallbladder" },
      { value: "pancreatitis", label: "Have had pancreatitis" },
      { value: "none", label: "None / NA" },
    ],
    required: true,
  },
  {
    id: 10,
    text: "Have you ever had any surgeries?",
    type: "radio",
    fieldName: "hadSurgeries",
    options: [
      { value: "yes", label: "Yes" },
      { value: "no", label: "No" },
    ],
    required: true,
  },
  {
    id: 11,
    text: "Have you had a provider listen to your heart and document a normal heart exam within the past 12 months?",
    type: "radio",
    fieldName: "normalHeartExam",
    options: [
      { value: "yes", label: "Yes" },
      { value: "no", label: "No" },
    ],
    required: true,
  },
  {
    id: 12,
    text: "Do you know your blood pressure range from within the last 6 months?",
    subtitle: "If taking blood pressure medication, this should be your range on medication.",
    type: "radio",
    fieldName: "bloodPressure",
    options: [
      { value: "low", label: "Low (Less than 90/60 mmHg)" },
      { value: "normal", label: "Normal (91-129/61-84 mmHg)" },
      { value: "high", label: "High (Higher than 130/85 mmHg)" },
      { value: "unknown", label: "I don't know" },
    ],
    required: true,
  },
  {
    id: 13,
    text: "What is your waist circumference?",
    subtitle: "You can measure your waist circumference at the level of your belly button.",
    type: "radio",
    fieldName: "waistCircumference",
    options: [
      { value: "less-than-35", label: "Less than 35 inches" },
      { value: "35-39", label: "35 - 39 inches" },
      { value: "40-or-more", label: "40 inches or more" },
      { value: "unknown", label: "I don't know" },
    ],
    required: true,
  },
  {
    id: 14,
    text: "Do you know your triglyceride levels?",
    subtitle: "Knowing your triglyceride levels can help us understand your risk of heart disease.",
    type: "radio",
    fieldName: "triglycerideLevel",
    options: [
      { value: "100-or-lower", label: "100 (mg/dL) or lower" },
      { value: "100-149", label: "100 - 149 (mg/dL)" },
      { value: "150-or-higher", label: "150 (mg/dL) or higher" },
      { value: "unknown", label: "I don't know" },
    ],
    required: true,
  },
  {
    id: 15,
    text: "Do you know your fasting blood sugar (glucose) level?",
    subtitle:
      "Checking your fasting glucose levels helps assess your risk for diabetes and understand how your body processes sugar.",
    type: "radio",
    fieldName: "fastingGlucose",
    options: [
      { value: "74-or-lower", label: "74 (mg/dL) or lower" },
      { value: "75-99", label: "75 - 99 (mg/dL)" },
      { value: "100-or-higher", label: "100 (mg/dL) or higher" },
      { value: "unknown", label: "I don't know" },
    ],
    required: true,
  },
  {
    id: 16,
    text: "Do you know your high-density lipoprotein (HDL) cholesterol level?",
    subtitle: "Monitoring HDL cholesterol levels is important for understanding cardiovascular health.",
    type: "radio",
    fieldName: "hdlCholesterol",
    options: [
      { value: "40-or-lower", label: "40 (mg/dL) or lower" },
      { value: "41-50", label: "41 - 50 (mg/dL)" },
      { value: "50-or-higher", label: "50 (mg/dL) or higher" },
      { value: "unknown", label: "I don't know" },
    ],
    required: true,
  },
  {
    id: 17,
    text: "How long have you been trying to lose weight?",
    type: "radio",
    fieldName: "weightLossHistory",
    options: [
      { value: "childhood", label: "Since childhood" },
      { value: "teens", label: "Since my teens" },
      { value: "adulthood", label: "Since adulthood (20s or later)" },
      { value: "children", label: "Since having children" },
      { value: "health-event", label: "Since a specific health event or recovery" },
      { value: "not-tried", label: "I haven't tried yet" },
    ],
    required: true,
  },
  {
    id: 18,
    text: "What is motivating you to lose weight?",
    subtitle: "Please check all that apply.",
    type: "checkbox-with-other",
    fieldName: "weightLossMotivation",
    options: [
      { value: "quality-of-life", label: "Improved quality of life" },
      { value: "fit-clothes", label: "Fit better in my clothes" },
      { value: "confidence", label: "Increased confidence" },
      { value: "energy", label: "Gain more energy" },
      { value: "family", label: "For my family / my kids" },
      { value: "health-concerns", label: "To address health concerns" },
      { value: "other", label: "Other" },
    ],
    otherFieldName: "otherMotivation",
    required: true,
  },
  {
    id: 19,
    text: "Have you had success with any of the following in the past?",
    subtitle: "Please check all that apply.",
    type: "checkbox",
    fieldName: "pastDietSuccess",
    options: [
      { value: "low-carb", label: "Low carb, such as keto, paleo, carnivore, Whole30, or Atkins" },
      { value: "intermittent-fasting", label: "Intermittent fasting" },
      { value: "high-protein", label: "High protein diet with low staples like rice/wheat" },
      { value: "nothing-worked", label: "Tried everything; nothing worked" },
      { value: "not-tried", label: "I haven't tried any of these" },
    ],
    required: true,
  },
  {
    id: 20,
    text: "How often do you exercise?",
    type: "radio",
    fieldName: "exerciseFrequency",
    options: [
      { value: "less-than-2x-month", label: "Less than 2x per month" },
      { value: "1x-week", label: "1x per week" },
      { value: "2-3x-week", label: "2-3x per week" },
      { value: "4-5x-week", label: "4-5x per week" },
      { value: "more-than-5x-week", label: "More than 5x per week" },
    ],
    required: true,
  },
  {
    id: 21,
    text: "Which categories of food and beverages do you have difficulty limiting in your diet?",
    subtitle: "Please check all that apply.",
    type: "checkbox",
    fieldName: "difficultFoods",
    options: [
      { value: "sweets", label: "Sweets (cookies, cake, ice cream, candy)" },
      { value: "salty-snacks", label: "Salty snacks (chips, pretzels, salted nuts)" },
      { value: "fast-food", label: "Fast food" },
      { value: "other-carbs", label: "Other carbs (cereal, pastries, bread, granola bars)" },
      { value: "fried-food", label: "Fried food (french fries, fried chicken, onion rings, fish sticks)" },
      { value: "sugary-drinks", label: "Sugary drinks (soda, fruit juice, energy drinks)" },
      { value: "dairy", label: "Dairy products (milk, yogurt, cheese)" },
      { value: "processed-meats", label: "Processed meats (sausage, bacon, cold cuts)" },
      { value: "alcohol", label: "Alcohol" },
      { value: "none", label: "None" },
    ],
    required: true,
  },
  {
    id: 22,
    text: "Do you have a hard time with portion control or with frequency of eating?",
    type: "radio",
    fieldName: "portionControl",
    options: [
      { value: "yes", label: "Yes" },
      { value: "no", label: "No" },
    ],
    required: true,
  },
  {
    id: 23,
    text: "When you have trouble controlling portions or frequency of eating, is any of the following true?",
    subtitle: "Please check all that apply.",
    type: "checkbox",
    fieldName: "eatingHabits",
    options: [
      { value: "never-full", label: "I never feel full" },
      { value: "constantly-eating", label: "I find myself constantly eating throughout the day" },
      { value: "bigger-portions", label: "My portions are always bigger than my peers" },
      {
        value: "never-full-meal",
        label: "I feel like no matter how much I eat at a meal, I never feel full by the end of the meal",
      },
      {
        value: "hungry-again",
        label: "I feel full after finishing a meal, but then shortly thereafter, I am very hungry again",
      },
      { value: "cant-stop", label: "Once I start eating something I feel as though I can't stop" },
    ],
    required: true,
  },
  {
    id: 24,
    text: "When do you tend to overeat or eat foods you are trying to avoid?",
    subtitle: "Please check all that apply.",
    type: "checkbox",
    fieldName: "overeatingTriggers",
    options: [
      { value: "emotional", label: "When I'm lonely, anxious, or depressed" },
      { value: "stress", label: "When I'm under stress" },
      { value: "angry", label: "When I'm angry or frustrated" },
      { value: "happy", label: "When I'm happy or excited" },
      { value: "alcohol", label: "When I drink alcohol" },
      { value: "night", label: "In the middle of the night" },
    ],
    required: true,
  },
  {
    id: 25,
    text: "How would you rate your quality of sleep?",
    type: "radio",
    fieldName: "sleepQuality",
    options: [
      { value: "very-poor", label: "Very poor" },
      { value: "poor", label: "Poor" },
      { value: "average", label: "Average" },
      { value: "good", label: "Good" },
      { value: "very-good", label: "Very good" },
    ],
    required: true,
  },
  {
    id: 26,
    text: "Which option best describes your energy level?",
    type: "radio",
    fieldName: "energyLevel",
    options: [
      { value: "hyper", label: "I tend to be hyper and restless" },
      { value: "tired", label: "I tend to be tired and lethargic" },
      { value: "neither", label: "Neither applies" },
    ],
    required: true,
  },
  {
    id: 27,
    text: "How many alcoholic beverages do you drink per week?",
    type: "radio",
    fieldName: "alcoholConsumption",
    options: [
      { value: "none", label: "None" },
      { value: "1-5", label: "1-5" },
      { value: "5-10", label: "5-10" },
      { value: "more-than-10", label: "> 10" },
    ],
    required: true,
  },
  {
    id: 28,
    text: "Do you smoke or use other tobacco or nicotine-containing products (including patches, pouches, gum, vapes, etc.)?",
    type: "radio",
    fieldName: "smokingStatus",
    options: [
      { value: "yes", label: "Yes" },
      { value: "no", label: "No" },
    ],
    required: true,
  },
  {
    id: 29,
    text: "What type of exercise do you do most often?",
    subtitle: "Please check all that apply.",
    type: "checkbox-with-other",
    fieldName: "exerciseType",
    options: [
      {
        value: "high-intensity",
        label: "High-intensity cardio (running, interval training, fast biking, rowing, or swimming)",
      },
      { value: "low-intensity", label: "Low-intensity cardio (walking, slow biking, slow elliptical)" },
      { value: "weight-training", label: "Weight training" },
      { value: "yoga", label: "Yoga or pilates" },
      { value: "other", label: "Other (please describe)" },
      { value: "none", label: "None" },
    ],
    otherFieldName: "otherExerciseType",
    required: true,
  },
  {
    id: 30,
    text: "What best describes your current eating habits?",
    type: "radio",
    fieldName: "eatingHabitsHealthy",
    options: [
      { value: "always", label: "I eat healthy all of the time" },
      { value: "most", label: "I eat healthy most of the time" },
      { value: "some", label: "I eat healthy some of the time" },
      { value: "rarely", label: "I rarely eat healthy" },
    ],
    required: true,
  },
  {
    id: 31,
    text: "I feel stressed..",
    type: "radio",
    fieldName: "stressLevel",
    options: [
      { value: "almost-always", label: "Almost always" },
      { value: "most", label: "Most of the time" },
      { value: "some", label: "Some of the time" },
      { value: "almost-never", label: "Almost never" },
      { value: "never", label: "Never" },
    ],
    required: true,
  },
  {
    id: 32,
    text: "Which of the following tends to guide your food choices most often?",
    subtitle: "Please check all that apply.",
    type: "checkbox",
    fieldName: "foodChoiceFactors",
    options: [
      { value: "convenience", label: "Convenience" },
      { value: "cost", label: "Cost" },
      { value: "appetite", label: "Appetite" },
      { value: "cravings", label: "Cravings" },
      { value: "family", label: "Family" },
      { value: "social", label: "Friends and social settings" },
      { value: "coworkers", label: "Coworkers" },
      { value: "nutrition", label: "Nutrition and health" },
    ],
    required: true,
  },
  {
    id: 33,
    text: "Who do you currently live with?",
    type: "radio",
    fieldName: "livingArrangement",
    options: [
      { value: "alone", label: "Me, myself, & I" },
      { value: "partner", label: "Spouse/partner" },
      { value: "with-children", label: "Family (with my children)" },
      { value: "with-parents", label: "Family (with my parents)" },
      { value: "multigenerational", label: "Multigenerational family" },
      { value: "roommates", label: "Friends/roommates" },
      { value: "coworkers", label: "Coworkers" },
    ],
    required: true,
  },
  {
    id: 34,
    text: "What is your typical work schedule?",
    type: "radio",
    fieldName: "workSchedule",
    options: [
      { value: "day", label: "Set hours during the day (8-6, 9-5, etc)" },
      { value: "night", label: "Night shift work" },
      { value: "variable", label: "Variable, pick my own hours" },
      { value: "dont-work", label: "I don't work" },
    ],
    required: true,
  },
  {
    id: 35,
    text: "What do you typically drink throughout the day?",
    subtitle: "Please check all that apply.",
    type: "checkbox",
    fieldName: "beverages",
    options: [
      { value: "regular-soda", label: "Regular soda" },
      { value: "smoothies", label: "Smoothies" },
      { value: "protein-shakes", label: "Protein shakes, protein water" },
      { value: "black-coffee", label: "Black coffee" },
      { value: "black-tea", label: "Black tea" },
      { value: "coffee-with-milk", label: "Espresso or coffee with milk or milk alternative" },
      { value: "green-tea", label: "Green tea" },
      { value: "diet-soda", label: "Diet Soda" },
      { value: "water", label: "Water" },
      { value: "juice", label: "Juice" },
      { value: "sparkling-water", label: "Sparkling water, infused water" },
      { value: "kombucha", label: "Kombucha, kefir, drinkable yogurt" },
      { value: "sports-drinks", label: "Sports drinks" },
      { value: "coconut-water", label: "Coconut water" },
      { value: "energy-drinks", label: "Energy drinks (Red Bull, etc.)" },
      { value: "yerba-mate", label: "Yerba mate" },
      { value: "alcohol", label: "Alcoholic beverages (beer, wine, or cocktails)" },
    ],
    required: true,
  },
  {
    id: 36,
    text: "On average, how many meals do you have per day?",
    type: "radio",
    fieldName: "mealsPerDay",
    options: [
      { value: "1-2", label: "1-2 meals" },
      { value: "3-4", label: "3-4 meals" },
      { value: "5-6", label: "5-6 meals" },
      { value: "7-or-more", label: "7 or more meals" },
      { value: "snack-instead", label: "I tend not to eat meals and snack instead" },
    ],
    required: true,
  },
  {
    id: 37,
    text: "On average, how many snacks do you have per day?",
    type: "radio",
    fieldName: "snacksPerDay",
    options: [
      { value: "1-2", label: "1-2 snacks" },
      { value: "3-4", label: "3-4 snacks" },
      { value: "5-6", label: "5-6 snacks" },
      { value: "7-or-more", label: "7 or more snacks" },
      { value: "no-snack", label: "I tend not to snack" },
    ],
    required: true,
  },
  {
    id: 38,
    text: "Do you ever eat after 10pm or before 7am?",
    type: "radio",
    fieldName: "lateNightEating",
    options: [
      { value: "every-night", label: "Every night" },
      { value: "most-nights", label: "Most nights" },
      { value: "some-nights", label: "Some nights" },
      { value: "rarely", label: "Rarely" },
      { value: "never", label: "Never" },
    ],
    required: true,
  },
  {
    id: 39,
    text: "Do you have a scale?",
    subtitle:
      "At Found, we do weekly weigh-ins to track your progress. We also encourage you to note your non-scale victories (NSVs) like energy, mood, sleep, and physical changes—these are also signs of improved health.",
    type: "radio",
    fieldName: "hasScale",
    options: [
      { value: "yes", label: "Yes" },
      { value: "no", label: "No" },
    ],
    required: true,
  },
]
